Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from myst_nb import glue

x = np.linspace(0, np.pi / 2, 1000)
y = np.sin(x) - x ** 3

Kd = 1.1
Kg = 2 - Kd
xd = [np.pi / 4, np.pi / 4 * Kd]
yd = np.sin(xd) - xd ** 3
xg = [np.pi / 4 * Kg, np.pi / 4]
yg = np.sin(xg) - xg ** 3
xc = [np.pi / 4 * Kg, np.pi / 4 * Kd]
xc2 = [np.pi / 4 * Kg, np.pi / 4, np.pi / 4 * Kd]
yc = np.sin(xc) - xc ** 3

f, ax = plt.subplots()
f.suptitle("D√©riv√©e √† droite")
ax.plot(y, x, linewidth=1.3, color=blue)
ax.plot(yd, xd, linewidth=1, color=red)
ax.set_xticks(xd, label=["x0", "x0+h"])
glue("deriv_d", f, display="False")

f, ax = plt.subplots()
f.suptitle("D√©riv√©e √† gauche")
ax.plot(y, x, linewidth=1.3, color=blue)
ax.plot(yg, xg, linewidth=1, color=red)
ax.set_xticks(xg, label=["x0-h", "x0"])
glue("deriv_g", f, display="False")

f, ax = plt.subplots()
f.suptitle("D√©riv√©e centr√©e")
ax.plot(y, x, linewidth=1.3, color=blue)
ax.plot(yc, xc, linewidth=1, color=red)
ax.set_xticks(xc2, label=["x0-h", "x0", "x0+h"])
glue("deriv_c", f, display="False")

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-b45192abe8b5>[0m in [0;36m<module>[0;34m[0m
[1;32m      9[0m [0mKg[0m [0;34m=[0m [0;36m2[0m [0;34m-[0m [0mKd[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0mxd[0m [0;34m=[0m [0;34m[[0m[0mnp[0m[0;34m.[0m[0mpi[0m [0;34m/[0m [0;36m4[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mpi[0m [0;34m/[0m [0;36m4[0m [0;34m*[0m [0mKd[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 11[0;31m [0myd[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0msin[0m[0;34m([0m[0mxd[0m[0;34m)[0m [0;34m-[0m [0mxd[0m [0;34m**[0m [0;36m3[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     12[0m [0mxg[0m [0;34m=[0m [0;34m[[0m[0mnp[0m[0;34m.[0m[0mpi[0m [0;34m/[0m [0;36m4[0m [0;34m*[0m [0mKg[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mpi[0m [0;34m/[0m [0;36m4[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0myg[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0msin[0m[0;34m([0m[0mxg[0m[0;34m)[0m [0;34m-[0m [0mxg[0m [0;34m**[0m [0;36m3[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: unsupported operand type(s) for ** or pow(): 'list' and 'int'
TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

