Traceback (most recent call last):
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\cedri\anaconda3\envs\prepa\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numpy import *
from matplotlib.pyplot import *
from scipy.integrate import odeint

def euler(f:callable, y0:float, t0: float, tf: float, pas:float) -> (numpy.ndarray, numpy.ndarray):
    tk = [t0]
    yk = [y0]
    while tk[-1] < tf:
        yk.append(yk[-1] + f(tk[-1], yk[-1]) * pas)
        tk.append(tk[-1] + pas)
    return array(tk), array(yk)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn [1], line 5[0m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mintegrate[39;00m [38;5;28;01mimport[39;00m odeint
[1;32m----> 5[0m [38;5;28;01mdef[39;00m [38;5;21meuler[39m(f:callable, y0:[38;5;28mfloat[39m, t0: [38;5;28mfloat[39m, tf: [38;5;28mfloat[39m, pas:[38;5;28mfloat[39m) [38;5;241m-[39m[38;5;241m>[39m ([43mnumpy[49m[38;5;241m.[39mndarray, numpy[38;5;241m.[39mndarray):
[0;32m      6[0m     tk [38;5;241m=[39m [t0]
[0;32m      7[0m     yk [38;5;241m=[39m [y0]

[1;31mNameError[0m: name 'numpy' is not defined
NameError: name 'numpy' is not defined

